
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Monster
 */
public class UrunEkrani extends javax.swing.JDialog {
    DefaultTableModel model;
    
    UrunIslemleri islemler = new UrunIslemleri();
    /**
     * Creates new form UrunEkrani
     */
    public UrunEkrani(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        model = (DefaultTableModel) urun_tablosu.getModel();
        bos_alani.setText("Merhaba " + Giris.KullanıcıAdı);
        urunGoruntule();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tur_alani = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        urun_tablosu = new javax.swing.JTable();
        arama_cubugu = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ad_alani = new javax.swing.JTextField();
        fiyat_alani = new javax.swing.JTextField();
        urunEkle = new javax.swing.JButton();
        mesaj_yazisi = new javax.swing.JTextField();
        urunGuncelle = new javax.swing.JButton();
        urunSıl = new javax.swing.JButton();
        tur_alanı = new javax.swing.JTextField();
        bos_alani = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tur_alani.setBackground(new java.awt.Color(23, 58, 86));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(195, 195, 195));
        jLabel1.setText("                      Stok Düzenleme Ekranı");

        urun_tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Ürün ", "Kategori", "Fiyat"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        urun_tablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                urun_tablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(urun_tablosu);
        if (urun_tablosu.getColumnModel().getColumnCount() > 0) {
            urun_tablosu.getColumnModel().getColumn(0).setResizable(false);
            urun_tablosu.getColumnModel().getColumn(1).setResizable(false);
            urun_tablosu.getColumnModel().getColumn(2).setResizable(false);
            urun_tablosu.getColumnModel().getColumn(3).setResizable(false);
        }

        arama_cubugu.setBackground(new java.awt.Color(23, 58, 86));
        arama_cubugu.setForeground(new java.awt.Color(195, 195, 195));
        arama_cubugu.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                arama_cubuguKeyReleased(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(195, 195, 195));
        jLabel2.setText("Ürün Adı : ");

        jLabel3.setForeground(new java.awt.Color(195, 195, 195));
        jLabel3.setText("Fiyat : ");

        jLabel4.setForeground(new java.awt.Color(195, 195, 195));
        jLabel4.setText("Kategori : ");

        ad_alani.setBackground(new java.awt.Color(195, 195, 195));

        fiyat_alani.setBackground(new java.awt.Color(195, 195, 195));

        urunEkle.setText("Ürün Ekle");
        urunEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urunEkleActionPerformed(evt);
            }
        });

        mesaj_yazisi.setBackground(new java.awt.Color(23, 58, 86));
        mesaj_yazisi.setForeground(new java.awt.Color(195, 195, 195));

        urunGuncelle.setText("Ürün Güncelle");
        urunGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urunGuncelleActionPerformed(evt);
            }
        });

        urunSıl.setText("Ürünü Sil");
        urunSıl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                urunSılActionPerformed(evt);
            }
        });

        tur_alanı.setBackground(new java.awt.Color(195, 195, 195));

        bos_alani.setBackground(new java.awt.Color(195, 195, 195));
        bos_alani.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        javax.swing.GroupLayout tur_alaniLayout = new javax.swing.GroupLayout(tur_alani);
        tur_alani.setLayout(tur_alaniLayout);
        tur_alaniLayout.setHorizontalGroup(
            tur_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tur_alaniLayout.createSequentialGroup()
                .addGroup(tur_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tur_alaniLayout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 628, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tur_alaniLayout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(arama_cubugu, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tur_alaniLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(tur_alaniLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(tur_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(tur_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 675, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(mesaj_yazisi, javax.swing.GroupLayout.PREFERRED_SIZE, 439, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(bos_alani, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(tur_alaniLayout.createSequentialGroup()
                                .addGroup(tur_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tur_alaniLayout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(fiyat_alani))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, tur_alaniLayout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(tur_alanı))
                                    .addGroup(tur_alaniLayout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(ad_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(tur_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tur_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(urunEkle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(urunGuncelle, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE))
                                    .addComponent(urunSıl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        tur_alaniLayout.setVerticalGroup(
            tur_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tur_alaniLayout.createSequentialGroup()
                .addGroup(tur_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(tur_alaniLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(bos_alani, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(arama_cubugu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tur_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ad_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(urunEkle))
                        .addGap(18, 18, 18)
                        .addGroup(tur_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(urunGuncelle)
                            .addComponent(tur_alanı, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(tur_alaniLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fiyat_alani, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tur_alaniLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(urunSıl)
                        .addGap(16, 16, 16)))
                .addComponent(mesaj_yazisi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tur_alani, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tur_alani, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public  void dinamikAra(String ara){
    
        TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
        
        
        urun_tablosu.setRowSorter(tr);
        
        
        tr.setRowFilter(RowFilter.regexFilter(ara));
        
    }
    private void arama_cubuguKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_arama_cubuguKeyReleased
        String ara = arama_cubugu.getText();
        
        dinamikAra(ara);
    }//GEN-LAST:event_arama_cubuguKeyReleased

    private void urunEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urunEkleActionPerformed
        mesaj_yazisi.setText("");
        
        String ad  =  ad_alani.getText();
        String kategori = tur_alanı.getText();
        String fiyat = fiyat_alani.getText();
        
        
        islemler.urunEkle(ad,kategori,fiyat);
        
        urunGoruntule();
        
        mesaj_yazisi.setText("Yeni ürün eklendi.");
    }//GEN-LAST:event_urunEkleActionPerformed

    private void urun_tablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_urun_tablosuMouseClicked
        int selectedrow = urun_tablosu.getSelectedRow();
        
        ad_alani.setText(model.getValueAt(selectedrow,1).toString());
        tur_alanı.setText(model.getValueAt(selectedrow,2).toString());
        fiyat_alani.setText(model.getValueAt(selectedrow,3).toString());
        
        
    }//GEN-LAST:event_urun_tablosuMouseClicked

    private void urunGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urunGuncelleActionPerformed
        String  urun = ad_alani.getText();
        String kategori = tur_alanı.getText();
        String fiyat = fiyat_alani.getText();
        
        
        int selectedrow = urun_tablosu.getSelectedRow();
        
        if (selectedrow == -1) {
            
            if (model.getRowCount() == 0) {
                mesaj_yazisi.setText("Ürünler Tablosu şu anda boş. ");
            }
            else {
                mesaj_yazisi.setText("Lütfen güncellenecek bir ürün seçin.");
            }
        }
        else {
            
            
            
            
            int ID = (int)model.getValueAt(selectedrow,0);
            
            
            
            islemler.urunGuncelle(ID,urun,kategori,fiyat);
            
            urunGoruntule();
            
            mesaj_yazisi.setText("Ürün başarıyla güncellendi...");
        }
        
        
        
    
    }//GEN-LAST:event_urunGuncelleActionPerformed

    private void urunSılActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_urunSılActionPerformed
        mesaj_yazisi.setText("");
       
       
       int selectedrow = urun_tablosu.getSelectedRow();
       
       if (selectedrow == -1) {
           if (model.getRowCount() == 0 ) {
               mesaj_yazisi.setText("Ürün tablosu şu anda boş.");
           }
           else {
               mesaj_yazisi.setText("Lütfen silinecek bir ürün seçin.");
           }
      
       }
       else {
           int ID = (int)model.getValueAt(selectedrow,0);
           
           islemler.urunSil(ID);
           
           urunGoruntule();
           
           mesaj_yazisi.setText("Ürün silindi.");
           
           
           
           
       }
        
    }//GEN-LAST:event_urunSılActionPerformed

    /**
     * @param args the command line arguments
     */
    public void urunGoruntule(){
    model.setRowCount(0);
        
        ArrayList<Urun> urunler = new ArrayList<Urun>();
        
        
        urunler = islemler.urunleriGetir();
        
        if (urunler != null ) {
            
            for (Urun urun : urunler) {
                Object[] eklenecek = {urun.getID(),urun.getUrun(),urun.getKategori(),urun.getFiyat()};
                
                model.addRow(eklenecek);
                
                
                
            }
            
        }
        
        
    }
        
    
    
    
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UrunEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UrunEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UrunEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UrunEkrani.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                UrunEkrani dialog = new UrunEkrani(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ad_alani;
    private javax.swing.JTextField arama_cubugu;
    private javax.swing.JLabel bos_alani;
    private javax.swing.JTextField fiyat_alani;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField mesaj_yazisi;
    private javax.swing.JPanel tur_alani;
    private javax.swing.JTextField tur_alanı;
    private javax.swing.JButton urunEkle;
    private javax.swing.JButton urunGuncelle;
    private javax.swing.JButton urunSıl;
    private javax.swing.JTable urun_tablosu;
    // End of variables declaration//GEN-END:variables
}
